// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzcuWW6yKIqshv_U_rWUOAxDJe9iQ4Pus',
    appId: '1:601158958002:web:cb077804e3916248ef42ab',
    messagingSenderId: '601158958002',
    projectId: 'little-mazedent',
    authDomain: 'little-mazedent.firebaseapp.com',
    storageBucket: 'little-mazedent.appspot.com',
    measurementId: 'G-MBJ1NREQZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoRieKeVcndpJBimW7oHpW1ivIFapwR4E',
    appId: '1:601158958002:android:c4221e87f6435794ef42ab',
    messagingSenderId: '601158958002',
    projectId: 'little-mazedent',
    storageBucket: 'little-mazedent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMoCSnpxGxkGDwqpWvrJiYv2vWcUb-428',
    appId: '1:601158958002:ios:68c82da71f7af1f9ef42ab',
    messagingSenderId: '601158958002',
    projectId: 'little-mazedent',
    storageBucket: 'little-mazedent.appspot.com',
    iosBundleId: 'com.dental.onetDental',
  );

}