// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3fHQToDv3tWFGn1JM3iaOrtx-NDkzeIU',
    appId: '1:437594142152:web:17ad0e0b8fdfd793f7fcfd',
    messagingSenderId: '437594142152',
    projectId: 'onet-dental-5503c',
    authDomain: 'onet-dental-5503c.firebaseapp.com',
    storageBucket: 'onet-dental-5503c.appspot.com',
    measurementId: 'G-DZLYSQ5YV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhh9t4WBi4YrmEg-FhaA-oLsVbYBqUCng',
    appId: '1:437594142152:android:67a1944eed11b3adf7fcfd',
    messagingSenderId: '437594142152',
    projectId: 'onet-dental-5503c',
    storageBucket: 'onet-dental-5503c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6eFQarvZLee3Yv9tl0KX9BmYeMKgeYy8',
    appId: '1:437594142152:ios:2082909177a83aa3f7fcfd',
    messagingSenderId: '437594142152',
    projectId: 'onet-dental-5503c',
    storageBucket: 'onet-dental-5503c.appspot.com',
    iosBundleId: 'com.dental.onetDental',
  );
}
